Paratii-Video/paratii-js

package.json

removing unused libs. fixes #51. 
Sorry for the inconvenience @bent0b0x & @jellegerbrandy

removing yt and vimeo grabber libs

---

dist/paratii.ipfs.uploader.js
lib/paratii.ipfs.uploader.js

`transcoding:error` instead of `transcoding:err`

syntax fix

---

dist/paratii.ipfs.js
dist/paratii.ipfs.uploader.js
docs/paratii-ipfs.md
lib/paratii.ipfs.js
lib/paratii.ipfs.uploader.js
test/paratii.core.vids.js
test/paratii.ipfs.uploader.js

pins JSON metadata. here is an example
```javascript
it('should be able to pin a JSON Object', (done) => {
paratiiIPFS.addJSON({test: 1}).then((multihash) => {
assert.isOk(multihash)
let ev = paratiiIPFS.uploader.pinFile(multihash)
ev.once('pin:error', done)
ev.once('pin:done', (hash) => {
expect(hash).to.equal(multihash)
done()
})
}).catch((err) => {
done(err)
})
})
```

ability to pin JSON

---

dist/paratii.core.js
dist/paratii.core.users.js
dist/paratii.core.vids.js
dist/paratii.db.js
dist/paratii.eth.js
dist/paratii.eth.users.js
dist/paratii.eth.vids.js
dist/paratii.eth.vouchers.js
dist/paratii.ipfs.js
dist/paratii.ipfs.uploader.js
dist/paratii.js
lib/paratii.core.js
lib/paratii.core.users.js
lib/paratii.core.vids.js
lib/paratii.db.js
lib/paratii.eth.js
lib/paratii.eth.users.js
lib/paratii.eth.vids.js
lib/paratii.eth.vouchers.js
lib/paratii.ipfs.js
lib/paratii.ipfs.uploader.js
lib/paratii.js
package.json
test/paratii.core.vids.js
yarn.lock

All dependencies on `default-options` have been eliminated in favor of `Joi`.

Refactored paratii-lib to verify code with Joi

---

dist/paratii.core.vids.js
dist/paratii.ipfs.js
lib/paratii.core.vids.js
lib/paratii.ipfs.js
package.json

this uses `ipfs.addAndPinJSON` instead of just `addJSON` to presist the files outside of the local browser IPFS repo. 
~~This also makes sure `owner` is the main `account.address` if not supplied.~~

add and pin json method

---

dist/paratii.eth.tcr.js
lib/paratii.eth.tcr.js

this provides a simple `checkEligiblityAndApply` function so `portal` can easily check if the user is eligible (ie has enough balance and approved TCR to get that balance) for staking or not.

check balances and allowances before staking

---

dist/paratii.ipfs.uploader.js
lib/paratii.ipfs.uploader.js

this should close https://github.com/Paratii-Video/paratii-portal/issues/186

fix for transcoder error triggered on multiple hashes

---

dist/paratii.eth.tcr.js
lib/paratii.eth.tcr.js
test/paratii.eth.tcr.js

this should work for https://github.com/Paratii-Video/paratii-portal/issues/227
__Note__ that i modified the test to check allowance after apply is triggered. this is to make sure the contract is functioning correctly.

fix for staking issue

---

dist/paratii.eth.js
dist/paratii.eth.tcr.js
dist/paratii.ipfs.uploader.js
lib/paratii.eth.js
lib/paratii.eth.tcr.js
lib/paratii.ipfs.uploader.js
test/paratii.eth.tcr.js
test/paratii.ipfs.uploader.js

promise instead of event emitter.
```javascript
paratii.ipfs.uploader.getMetaData(testHash, {}).then((data) => {
assert.isOk(data)
console.log(data)
done()
}).catch(done)
```

promisify getMetaData

---

dist/paratii.eth.tcr.js
lib/paratii.eth.tcr.js

this uses BigNumber `.lt` function. this is safer than using numbers due to javascript limitations.

use BN.js comparators instead of js ones

---

dist/paratii.ipfs.uploader.js
lib/paratii.ipfs.uploader.js

this makes sure the state is for the hash in question.

check hash before emitting

---

dist/paratii.ipfs.js
dist/paratii.ipfs.uploader.js
lib/paratii.ipfs.js
lib/paratii.ipfs.uploader.js
package-lock.json
package.json

this isn't ready till `uploader.paratii.video` DNS is setup and running first. (https)

express uploader. for ppl who don't wanna wait.

---

dist/paratii.ipfs.uploader.js
lib/paratii.ipfs.uploader.js

this limits the video uploaded to 300MB.

uploader limited to 300mb

---

dist/paratii.ipfs.js
dist/paratii.ipfs.local.js
dist/paratii.ipfs.remote.js
dist/paratii.transcoder.js
src/paratii.ipfs.js
src/paratii.ipfs.local.js
src/paratii.ipfs.remote.js
src/paratii.transcoder.js

changed a few descriptions
added a few todos so we can locate things better
removed getMetadata from paratii.transcoder (it was already present in paratii.ipfs.remote)

Creating jsdoc

---

src/paratii.db.vids.js

**Issue**
#218 
**Work Done**
- update joi types of limit and offset to be integers

218 - update types for limit and offset in search

---

.gitignore
dist/paratii.eth.js
dist/paratii.eth.tcr.js
package-lock.json
package.json
src/paratii.eth.js
src/paratii.eth.tcr.js
test/paratii.eth.tcr.js

**DO NOT MERGE**
this is a work in progress 
functions:

Tcr integration wip

---

dist/paratii.eth.tcr.js
src/paratii.eth.tcr.js

changed some normal number to BN

---

package-lock.json
package.json

this way rebuild should happen only if file are changed

changed build process

---

dist/paratii.ipfs.js
dist/paratii.ipfs.local.js
dist/paratii.ipfs.remote.js
dist/paratii.transcoder.js
dist/schemas.js
src/paratii.ipfs.js
src/paratii.ipfs.local.js
src/paratii.ipfs.remote.js
src/paratii.transcoder.js
src/schemas.js
test/paratii.core.vids.js

uploader ugly af fix, work in progress

---

dist/paratii.eth.tcr.js
src/paratii.eth.tcr.js

**Issue**
#296 
**Work Done**
- remove one loop from calculation of staked PTI

296 - remove loop from staked calculation
